DROP TABLE IF EXISTS radars;
DROP TABLE IF EXISTS activities;

CREATE TABLE radars (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    is_connected BOOLEAN NOT NULL,
    name TEXT NOT NULL,
    location TEXT NOT NULL,
    last_active DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE activities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    radar_id INTEGER NOT NULL,
    activity_type TEXT NOT NULL,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (radar_id) REFERENCES radars (id) ON DELETE CASCADE
);